In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

print("All libraries successfully imported!")

All libraries successfully imported!

In [ ]:
week29_data = pd.read_excel("food2_week29.xlsx")
week29_data = week29_data.reset_index(drop=True)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
week29_data

,"Food Table 2. Food Sufficiency for Households, in the Last 7 Days, by Select Characteristics: United States",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Source: U.S. Census Bureau Household Pulse Sur...,NaN,NaN,NaN,NaN,NaN,NaN
1,Note: These data are experimental. Users shoul...,NaN,NaN,NaN,NaN,NaN,NaN
2,Total Population 18 Years and Older,NaN,NaN,NaN,NaN,NaN,NaN
3,Select characteristics,Total,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days
4,NaN,NaN,Enough of the types of food wanted,"Enough food, but not always the types wanted",Sometimes not enough to eat,Often not enough to eat,Did not report
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Total,250265449,148971592,41703471,14614514,3582870,41393001
7,Age,NaN,NaN,NaN,NaN,NaN,NaN
8,18 - 24,23445638,10283478,3717851,1306372,208437,7929500
9,25 - 39,65230956,35997802,11383198,4979996,1190071,11679888
10,40 - 54,63471403,36427026,11471318,4762734,1216737,9593588
11,55 - 64,42533760,26711466,7157102,2222868,486280,5956044
12,65 and above,55583692,39551820,7974001,1342545,481345,6233981
13,Sex,NaN,NaN,NaN,NaN,NaN,NaN
14,Male,121078275,73914087,18281982,6737192,1766807,20378206
15,Female,129187174,75057505,23421489,7877322,1816063,21014795
16,Hispanic origin and Race,NaN,NaN,NaN,NaN,NaN,NaN
17,Hispanic or Latino (may be of any race),43041957,18967539,9084155,4246360,1110912,9632989
18,"White alone, not Hispanic",155928642,104338242,22705002,6350498,1521784,21013116
19,"Black alone, not Hispanic",28569240,12831883,5647250,2935839,594363,6559906
20,"Asian alone, not Hispanic",13703920,8172589,2306217,384873,110861,2729380
21,"Two or more races + Other races, not Hispanic",9021690,4661338,1960847,696945,244951,1457609
22,Education,NaN,NaN,NaN,NaN,NaN,NaN
23,Less than high school,20156177,7429472,4370675,2471776,1006740,4877513
24,High school or GED,77288442,40721363,13942126,6139767,1108752,15376434
25,Some college/associate’s degree,75567240,42849643,14696746,4576649,996434,12447768
26,Bachelor’s degree or higher,77253590,57971115,8693924,1426322,470944,8691286
27,Marital status,NaN,NaN,NaN,NaN,NaN,NaN
28,Married,137508149,91970616,19925438,5096925,1090883,19424288
29,Widowed,11416098,6489146,2469913,671313,171667,1614060
30,Divorced/separated,32451688,16771199,7061173,3353805,754203,4511308
31,Never married,65958874,32669713,12046048,5400856,1543763,14298495
32,Did not report,2930639,1070919,200899,91616,22354,1544851
33,Household size,NaN,NaN,NaN,NaN,NaN,NaN
34,1 person in the household,19603284,11916336,3342264,1179531,322022,2843131
35,2 people in the household,79400506,54124919,11111614,3174361,668392,10321220
36,3 people in the household,48788164,29269648,8097954,2578490,699099,8142974
37,4 people in the household,49463241,28477869,8093862,3035426,642273,9213811
38,5 people in the household,26794550,14007831,5641518,1889697,265126,4990378
39,6 people in the household,13644057,5967323,2923923,1284918,204168,3263724
40,7 or more people in the household,12571646,5207666,2492336,1472092,781789,2617762
41,Presence of children under 18 years old,NaN,NaN,NaN,NaN,NaN,NaN
42,Children in household,96993159,51220738,18509098,7119103,1727913,18416307
43,No children,153272290,97750854,23194373,7495411,1854957,22976694
44,Respondent or household member experienced los...,NaN,NaN,NaN,NaN,NaN,NaN
45,Yes,48246124,16495251,12718184,7250542,1927595,9854552
46,No,200243849,132184536,28885085,7340792,1616795,30216641
47,Did not report,1775475,291805,100202,23180,38481,1321808
48,Respondent currently employed,NaN,NaN,NaN,NaN,NaN,NaN
49,Yes,146518424,93085368,21844409,7077966,1369954,23140727
50,No,101655976,55575346,19812347,7508598,2111272,16648412
51,Did not report,2091049,310878,46715,27950,101644,1603862
52,Reason for not working,NaN,NaN,NaN,NaN,NaN,NaN
53,I did not want to be employed at this time,5790358,3390714,525071,126789,219323,1528462
54,I was caring for someone or sick myself wi...,2140725,596391,640710,327313,153254,423058
55,I was caring for children not in school or...,6894328,2851336,1583119,770918,167030,1521925
56,I was caring for an elderly person,2455616,1025344,593293,360620,69773,406586
57,I was concerned about getting or spreading...,3527987,1115409,1230971,425756,91237,664614
58,I was sick (not coronavirus related) or di...,6722545,2317380,2325786,952557,297695,829127
59,I am retired,42189378,31424306,5634389,890413,88532,4151738
60,I was laid off or furloughed due to corona...,7218299,2586018,2085350,892520,182851,1471560
61,My employer closed temporarily due to the ...,2740044,904449,604005,476477,91926,663188
62,My employer went out of business due to th...,2040314,429186,513804,518718,176553,402052
63,I did not have tranportation to work,828852,202681,142581,157207,57841,268542
64,Other reason,16620625,7859047,3596568,1408095,474800,3282115
65,Did not report reason,151096377,94269333,22227824,7307130,1512056,25780035
66,Household income,NaN,NaN,NaN,NaN,NaN,NaN
67,"Less than $25,000",23732207,10515340,7528310,4389243,1223597,75718
68,"$25,000 - $34,999",18636048,10043422,5433349,2487504,562012,109760
69,"$35,000 - $49,999",20811511,13141059,5535377,1860203,263995,10877
70,"$50,000 - $74,999",28507113,21090818,5909950,1311151,176337,18856
71,"$75,000 - $99,999",22332718,17991880,3611709,623690,73919,31521
72,"$100,000 - $149,999",25329184,22142307,2669270,394102,107075,16430
73,"$150,000 - $199,999",11861913,10869429,914863,60714,9083,7824
74,"$200,000 and above",12896711,12195005,601818,31531,64377,3980
75,Did not report,86158044,30982332,9498824,3456377,1102476,41118036
76,Used in the last 7 days to meet spending needs*,NaN,NaN,NaN,NaN,NaN,NaN
77,Regular income sources like those received...,157720993,125757576,24278613,5421285,990163,1273357
78,Credit cards or loans,54645825,32294484,15587943,5174040,1054888,534470
79,Money from savings or selling assets or po...,41521270,21636887,13793144,4594597,1040768,455875
80,Borrowing from friends or family,18837177,4405538,6426890,6266183,1536510,202055
81,Unemployment insurance (UI) benefit payments,15322178,7581719,5115826,1989045,415869,219718
82,Stimulus (economic impact) payment,58589746,32444836,18071086,6320701,1188932,564190
83,Money saved from deferred or forgiven paym...,6831229,3178119,2445455,812501,258268,136886
84,Supplemental Nutrition Assistance Program ...,13065439,4941992,4658697,2624601,637683,202466
85,Other,6356731,3248901,1496760,784212,677831,149027
86,Did not report,43237640,2911323,647694,359103,217426,39102093
87,Active duty military*,NaN,NaN,NaN,NaN,NaN,NaN
88,Serving on active duty,966642,512167,149455,19610,119552,165857
89,Serving in Reserve or National Guard,827297,549962,143424,39382,14103,80426
90,Spouse serving on active duty,934933,580291,107879,99909,14685,132169
91,Spouse serving in Reserve or National Guard,689898,388914,67020,18950,18659,196356
92,No active duty service (self or spouse),244383217,146303917,40993490,14412920,3436674,39236216
93,Did not report,3150041,1043599,310566,64162,52965,1678749
94,Difficulty seeing,NaN,NaN,NaN,NaN,NaN,NaN
95,No difficulty,123655534,97174748,19437462,5769585,1087688,186051
96,Some difficulty,49583321,29963285,13727536,4792456,1050714,49331
97,A lot of difficulty,5888001,2635373,1642055,1148920,420565,41088
98,Cannot do at all,858969,286827,75305,221710,269902,5225
99,Did not report,70279625,18911360,6821112,2681843,754002,41111308
100,Difficulty hearing,NaN,NaN,NaN,NaN,NaN,NaN
101,No difficulty,151752118,112509535,27888381,9343380,1812748,198075
102,Some difficulty,23471205,15506729,5606239,1813513,512636,32087
103,A lot of difficulty,3527416,1509134,1003846,541783,439969,32684
104,Cannot do at all,857265,284092,286062,212115,64273,10725
105,Did not report,70657444,19162102,6918943,2703723,753245,41119431
106,Difficulty remembering or concentrating,NaN,NaN,NaN,NaN,NaN,NaN
107,No difficulty,109164519,86695007,16626439,4857273,813873,171927
108,Some difficulty,60325715,38374630,15205894,5413335,1279467,52389
109,A lot of difficulty,9586364,4541967,2894254,1526941,585949,37253
110,Cannot do at all,627694,287394,49335,133355,146886,10725
111,Did not report,70561157,19072595,6927548,2683611,756695,41120707
112,Difficulty walking or climbing stairs,NaN,NaN,NaN,NaN,NaN,NaN
113,No difficulty,135876470,104682641,22463033,7260031,1308550,162214
114,Some difficulty,33355591,20923452,8735026,2887778,747502,61833
115,A lot of difficulty,9652368,3895053,3415221,1619154,682248,40693
116,Cannot do at all,1027549,492021,254128,177113,95173,9113
117,Did not report,70353470,18978425,6836062,2670438,749397,41119148
118,Household receives benefits from the Supplemen...,NaN,NaN,NaN,NaN,NaN,NaN
119,Yes,24482444,10825575,8046708,4427348,1088248,94565
120,No,181572364,136107958,32726968,10015474,2310916,411049
121,Did not report,44210641,2038059,929795,171693,183707,40887388
122,"Frequency of feeling nervous, anxious, on edge",NaN,NaN,NaN,NaN,NaN,NaN
123,Not at all,90263384,77668430,9583043,2278526,524464,208920
124,Several days,52338911,35717943,12680023,3565303,273260,102383
125,More than half the days,20249537,10954171,6292711,2564305,420540,17809
126,Nearly every day,28258033,12684293,8699356,4878902,1945722,49760
127,Did not report,59155584,11946754,4448338,1327478,418884,41014129
128,Frequency of not being able to stop or control...,NaN,NaN,NaN,NaN,NaN,NaN
129,Not at all,103168903,88422301,11555526,2602094,396986,191996
130,Several days,49269556,31356198,13285655,4102012,452578,73112
131,More than half the days,17330000,8491332,5774867,2659202,351118,53481
132,Nearly every day,20988592,8450420,6583582,3951618,1966709,36262
133,Did not report,59508399,12251341,4503841,1299588,415479,41038150
134,Frequency of having little interest or pleasur...,NaN,NaN,NaN,NaN,NaN,NaN
135,Not at all,102929917,87714045,11711125,2872833,465319,166594
136,Several days,49897598,32024124,13411922,3916892,449096,95563
137,More than half the days,18859692,9164616,6306887,2758787,611990,17411
138,Nearly every day,19088384,7806297,5844296,3764796,1640986,32010
139,Did not report,59489858,12262509,4429241,1301207,415479,41081423
140,"Frequency of feeling down, depressed, or hopel...",NaN,NaN,NaN,NaN,NaN,NaN
141,Not at all,106634633,89536894,13163653,3248242,509821,176022
142,Several days,49505510,31486509,13472389,4026857,433689,86065
143,More than half the days,15507817,7548804,5138902,2158216,648408,13487
144,Nearly every day,19054537,8073877,5491665,3883076,1575474,30446
145,Did not report,59562952,12325507,4436862,1298123,415479,41086981
146,Covered by health insurance,NaN,NaN,NaN,NaN,NaN,NaN
147,Yes,168220845,125001251,31314225,9441900,2166257,297212
148,No,17283920,8186766,4911955,3246164,914514,24522
149,Did not report or don’t know,64760684,15783575,5477291,1926451,502099,41071268
150,Currently caught up on mortgage or rental paym...,NaN,NaN,NaN,NaN,NaN,NaN
151,Yes,116227244,85549104,23458351,6195048,865384,159357
152,No,13519982,5009342,4145456,3183110,1165593,16481
153,Housing owned or payment not required,47064251,37341223,6679673,2279226,686117,78012
154,Did not report,73453972,21071923,7419991,2957130,865777,41139151
155,Confidence in paying next rent or mortgage,NaN,NaN,NaN,NaN,NaN,NaN
156,No confidence,7295904,1993163,2309759,2209059,779170,4754
157,Slight confidence,12555854,3821639,5218748,3015758,480722,18987
158,Moderate confidence,21632362,9681840,8967731,2641838,330032,10921
159,High confidence,86025320,73466635,10637799,1384488,397750,138647
160,Payment is/will be deferred,1935686,1336268,431823,125889,41453,253
161,Did not report,120820323,58672047,14137611,5237482,1553743,41219440
162,Free groceries or free meal in last 7 days,NaN,NaN,NaN,NaN,NaN,NaN
163,Yes,17273594,6500672,6154438,3866752,712425,39307
164,No,190597179,141872055,34958323,10586286,2724916,455599
165,Did not report,42394677,598865,590710,161477,145530,40898095
166,* Totals may not sum to 100% as the question a...,NaN,NaN,NaN,NaN,NaN,NaN
167,** The Census Bureau considers estimated coeff...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Drop duplicate information
week29_data = week29_data.drop_duplicates()

In [ ]:
# Drop unecessary information line
week29_data.drop(week29_data.index[1], inplace=True)

# Drop unecessary mortgage and free grocery information (not necessary to the analysis)
week29_data.drop(week29_data.index[149:167], inplace=True)

In [ ]:
# Drop active duty information
week29_data.drop(week29_data.index[86:117], inplace=True)

In [ ]:
# Reset index to locate proper indices
week29_data = week29_data.reset_index(drop=True)
week29_data

,"Food Table 2. Food Sufficiency for Households, in the Last 7 Days, by Select Characteristics: United States",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Source: U.S. Census Bureau Household Pulse Sur...,NaN,NaN,NaN,NaN,NaN,NaN
1,Total Population 18 Years and Older,NaN,NaN,NaN,NaN,NaN,NaN
2,Select characteristics,Total,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days
3,NaN,NaN,Enough of the types of food wanted,"Enough food, but not always the types wanted",Sometimes not enough to eat,Often not enough to eat,Did not report
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Total,250265449,148971592,41703471,14614514,3582870,41393001
6,Age,NaN,NaN,NaN,NaN,NaN,NaN
7,18 - 24,23445638,10283478,3717851,1306372,208437,7929500
8,25 - 39,65230956,35997802,11383198,4979996,1190071,11679888
9,40 - 54,63471403,36427026,11471318,4762734,1216737,9593588
10,55 - 64,42533760,26711466,7157102,2222868,486280,5956044
11,65 and above,55583692,39551820,7974001,1342545,481345,6233981
12,Sex,NaN,NaN,NaN,NaN,NaN,NaN
13,Male,121078275,73914087,18281982,6737192,1766807,20378206
14,Female,129187174,75057505,23421489,7877322,1816063,21014795
15,Hispanic origin and Race,NaN,NaN,NaN,NaN,NaN,NaN
16,Hispanic or Latino (may be of any race),43041957,18967539,9084155,4246360,1110912,9632989
17,"White alone, not Hispanic",155928642,104338242,22705002,6350498,1521784,21013116
18,"Black alone, not Hispanic",28569240,12831883,5647250,2935839,594363,6559906
19,"Asian alone, not Hispanic",13703920,8172589,2306217,384873,110861,2729380
20,"Two or more races + Other races, not Hispanic",9021690,4661338,1960847,696945,244951,1457609
21,Education,NaN,NaN,NaN,NaN,NaN,NaN
22,Less than high school,20156177,7429472,4370675,2471776,1006740,4877513
23,High school or GED,77288442,40721363,13942126,6139767,1108752,15376434
24,Some college/associate’s degree,75567240,42849643,14696746,4576649,996434,12447768
25,Bachelor’s degree or higher,77253590,57971115,8693924,1426322,470944,8691286
26,Marital status,NaN,NaN,NaN,NaN,NaN,NaN
27,Married,137508149,91970616,19925438,5096925,1090883,19424288
28,Widowed,11416098,6489146,2469913,671313,171667,1614060
29,Divorced/separated,32451688,16771199,7061173,3353805,754203,4511308
30,Never married,65958874,32669713,12046048,5400856,1543763,14298495
31,Did not report,2930639,1070919,200899,91616,22354,1544851
32,Household size,NaN,NaN,NaN,NaN,NaN,NaN
33,1 person in the household,19603284,11916336,3342264,1179531,322022,2843131
34,2 people in the household,79400506,54124919,11111614,3174361,668392,10321220
35,3 people in the household,48788164,29269648,8097954,2578490,699099,8142974
36,4 people in the household,49463241,28477869,8093862,3035426,642273,9213811
37,5 people in the household,26794550,14007831,5641518,1889697,265126,4990378
38,6 people in the household,13644057,5967323,2923923,1284918,204168,3263724
39,7 or more people in the household,12571646,5207666,2492336,1472092,781789,2617762
40,Presence of children under 18 years old,NaN,NaN,NaN,NaN,NaN,NaN
41,Children in household,96993159,51220738,18509098,7119103,1727913,18416307
42,No children,153272290,97750854,23194373,7495411,1854957,22976694
43,Respondent or household member experienced los...,NaN,NaN,NaN,NaN,NaN,NaN
44,Yes,48246124,16495251,12718184,7250542,1927595,9854552
45,No,200243849,132184536,28885085,7340792,1616795,30216641
46,Did not report,1775475,291805,100202,23180,38481,1321808
47,Respondent currently employed,NaN,NaN,NaN,NaN,NaN,NaN
48,Yes,146518424,93085368,21844409,7077966,1369954,23140727
49,No,101655976,55575346,19812347,7508598,2111272,16648412
50,Did not report,2091049,310878,46715,27950,101644,1603862
51,Reason for not working,NaN,NaN,NaN,NaN,NaN,NaN
52,I did not want to be employed at this time,5790358,3390714,525071,126789,219323,1528462
53,I was caring for someone or sick myself wi...,2140725,596391,640710,327313,153254,423058
54,I was caring for children not in school or...,6894328,2851336,1583119,770918,167030,1521925
55,I was caring for an elderly person,2455616,1025344,593293,360620,69773,406586
56,I was concerned about getting or spreading...,3527987,1115409,1230971,425756,91237,664614
57,I was sick (not coronavirus related) or di...,6722545,2317380,2325786,952557,297695,829127
58,I am retired,42189378,31424306,5634389,890413,88532,4151738
59,I was laid off or furloughed due to corona...,7218299,2586018,2085350,892520,182851,1471560
60,My employer closed temporarily due to the ...,2740044,904449,604005,476477,91926,663188
61,My employer went out of business due to th...,2040314,429186,513804,518718,176553,402052
62,I did not have tranportation to work,828852,202681,142581,157207,57841,268542
63,Other reason,16620625,7859047,3596568,1408095,474800,3282115
64,Did not report reason,151096377,94269333,22227824,7307130,1512056,25780035
65,Household income,NaN,NaN,NaN,NaN,NaN,NaN
66,"Less than $25,000",23732207,10515340,7528310,4389243,1223597,75718
67,"$25,000 - $34,999",18636048,10043422,5433349,2487504,562012,109760
68,"$35,000 - $49,999",20811511,13141059,5535377,1860203,263995,10877
69,"$50,000 - $74,999",28507113,21090818,5909950,1311151,176337,18856
70,"$75,000 - $99,999",22332718,17991880,3611709,623690,73919,31521
71,"$100,000 - $149,999",25329184,22142307,2669270,394102,107075,16430
72,"$150,000 - $199,999",11861913,10869429,914863,60714,9083,7824
73,"$200,000 and above",12896711,12195005,601818,31531,64377,3980
74,Did not report,86158044,30982332,9498824,3456377,1102476,41118036
75,Used in the last 7 days to meet spending needs*,NaN,NaN,NaN,NaN,NaN,NaN
76,Regular income sources like those received...,157720993,125757576,24278613,5421285,990163,1273357
77,Credit cards or loans,54645825,32294484,15587943,5174040,1054888,534470
78,Money from savings or selling assets or po...,41521270,21636887,13793144,4594597,1040768,455875
79,Borrowing from friends or family,18837177,4405538,6426890,6266183,1536510,202055
80,Unemployment insurance (UI) benefit payments,15322178,7581719,5115826,1989045,415869,219718
81,Stimulus (economic impact) payment,58589746,32444836,18071086,6320701,1188932,564190
82,Money saved from deferred or forgiven paym...,6831229,3178119,2445455,812501,258268,136886
83,Supplemental Nutrition Assistance Program ...,13065439,4941992,4658697,2624601,637683,202466
84,Other,6356731,3248901,1496760,784212,677831,149027
85,Did not report,43237640,2911323,647694,359103,217426,39102093
86,Household receives benefits from the Supplemen...,NaN,NaN,NaN,NaN,NaN,NaN
87,Yes,24482444,10825575,8046708,4427348,1088248,94565
88,No,181572364,136107958,32726968,10015474,2310916,411049
89,Did not report,44210641,2038059,929795,171693,183707,40887388
90,"Frequency of feeling nervous, anxious, on edge",NaN,NaN,NaN,NaN,NaN,NaN
91,Not at all,90263384,77668430,9583043,2278526,524464,208920
92,Several days,52338911,35717943,12680023,3565303,273260,102383
93,More than half the days,20249537,10954171,6292711,2564305,420540,17809
94,Nearly every day,28258033,12684293,8699356,4878902,1945722,49760
95,Did not report,59155584,11946754,4448338,1327478,418884,41014129
96,Frequency of not being able to stop or control...,NaN,NaN,NaN,NaN,NaN,NaN
97,Not at all,103168903,88422301,11555526,2602094,396986,191996
98,Several days,49269556,31356198,13285655,4102012,452578,73112
99,More than half the days,17330000,8491332,5774867,2659202,351118,53481
100,Nearly every day,20988592,8450420,6583582,3951618,1966709,36262
101,Did not report,59508399,12251341,4503841,1299588,415479,41038150
102,Frequency of having little interest or pleasur...,NaN,NaN,NaN,NaN,NaN,NaN
103,Not at all,102929917,87714045,11711125,2872833,465319,166594
104,Several days,49897598,32024124,13411922,3916892,449096,95563
105,More than half the days,18859692,9164616,6306887,2758787,611990,17411
106,Nearly every day,19088384,7806297,5844296,3764796,1640986,32010
107,Did not report,59489858,12262509,4429241,1301207,415479,41081423
108,"Frequency of feeling down, depressed, or hopel...",NaN,NaN,NaN,NaN,NaN,NaN
109,Not at all,106634633,89536894,13163653,3248242,509821,176022
110,Several days,49505510,31486509,13472389,4026857,433689,86065
111,More than half the days,15507817,7548804,5138902,2158216,648408,13487
112,Nearly every day,19054537,8073877,5491665,3883076,1575474,30446
113,Did not report,59562952,12325507,4436862,1298123,415479,41086981
114,Covered by health insurance,NaN,NaN,NaN,NaN,NaN,NaN
115,Yes,168220845,125001251,31314225,9441900,2166257,297212
116,No,17283920,8186766,4911955,3246164,914514,24522
117,Did not report or don’t know,64760684,15783575,5477291,1926451,502099,41071268

In [ ]:
# Drop information regarding respondent sentiments except "Frequency of feeling nervous...."
week29_data.drop(week29_data.index[95:113], inplace=True)

In [ ]:
# Combine households of 5-7
rows_to_combine = [37, 38, 39]

rows_data = week29_data.iloc[rows_to_combine]

combined_row = ['5-7 people in the household'] + rows_data.iloc[:, 1:].sum().tolist()

week29_data.drop(rows_to_combine, inplace=True)

week29_data = week29_data.reset_index(drop=True)

week29_data.loc[37] = combined_row

week29_data = week29_data.sort_index().reset_index(drop=True)

In [ ]:
# Drop null values from table
week29_data.fillna('')

,"Food Table 2. Food Sufficiency for Households, in the Last 7 Days, by Select Characteristics: United States",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Source: U.S. Census Bureau Household Pulse Sur...,,,,,,
1,Total Population 18 Years and Older,,,,,,
2,Select characteristics,Total,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days,Food sufficiency in the last 7 days
3,,,Enough of the types of food wanted,"Enough food, but not always the types wanted",Sometimes not enough to eat,Often not enough to eat,Did not report
4,,,,,,,
5,Total,250265449,148971592,41703471,14614514,3582870,41393001
6,Age,,,,,,
7,18 - 24,23445638,10283478,3717851,1306372,208437,7929500
8,25 - 39,65230956,35997802,11383198,4979996,1190071,11679888
9,40 - 54,63471403,36427026,11471318,4762734,1216737,9593588
10,55 - 64,42533760,26711466,7157102,2222868,486280,5956044
11,65 and above,55583692,39551820,7974001,1342545,481345,6233981
12,Sex,,,,,,
13,Male,121078275,73914087,18281982,6737192,1766807,20378206
14,Female,129187174,75057505,23421489,7877322,1816063,21014795
15,Hispanic origin and Race,,,,,,
16,Hispanic or Latino (may be of any race),43041957,18967539,9084155,4246360,1110912,9632989
17,"White alone, not Hispanic",155928642,104338242,22705002,6350498,1521784,21013116
18,"Black alone, not Hispanic",28569240,12831883,5647250,2935839,594363,6559906
19,"Asian alone, not Hispanic",13703920,8172589,2306217,384873,110861,2729380
20,"Two or more races + Other races, not Hispanic",9021690,4661338,1960847,696945,244951,1457609
21,Education,,,,,,
22,Less than high school,20156177,7429472,4370675,2471776,1006740,4877513
23,High school or GED,77288442,40721363,13942126,6139767,1108752,15376434
24,Some college/associate’s degree,75567240,42849643,14696746,4576649,996434,12447768
25,Bachelor’s degree or higher,77253590,57971115,8693924,1426322,470944,8691286
26,Marital status,,,,,,
27,Married,137508149,91970616,19925438,5096925,1090883,19424288
28,Widowed,11416098,6489146,2469913,671313,171667,1614060
29,Divorced/separated,32451688,16771199,7061173,3353805,754203,4511308
30,Never married,65958874,32669713,12046048,5400856,1543763,14298495
31,Did not report,2930639,1070919,200899,91616,22354,1544851
32,Household size,,,,,,
33,1 person in the household,19603284,11916336,3342264,1179531,322022,2843131
34,2 people in the household,79400506,54124919,11111614,3174361,668392,10321220
35,3 people in the household,48788164,29269648,8097954,2578490,699099,8142974
36,4 people in the household,49463241,28477869,8093862,3035426,642273,9213811
37,5-7 people in the household,53010253,25182820,11057777,4646707,1251083,10871864
38,Children in household,96993159,51220738,18509098,7119103,1727913,18416307
39,No children,153272290,97750854,23194373,7495411,1854957,22976694
40,Respondent or household member experienced los...,,,,,,
41,Yes,48246124,16495251,12718184,7250542,1927595,9854552
42,No,200243849,132184536,28885085,7340792,1616795,30216641
43,Did not report,1775475,291805,100202,23180,38481,1321808
44,Respondent currently employed,,,,,,
45,Yes,146518424,93085368,21844409,7077966,1369954,23140727
46,No,101655976,55575346,19812347,7508598,2111272,16648412
47,Did not report,2091049,310878,46715,27950,101644,1603862
48,Reason for not working,,,,,,
49,I did not want to be employed at this time,5790358,3390714,525071,126789,219323,1528462
50,I was caring for someone or sick myself wi...,2140725,596391,640710,327313,153254,423058
51,I was caring for children not in school or...,6894328,2851336,1583119,770918,167030,1521925
52,I was caring for an elderly person,2455616,1025344,593293,360620,69773,406586
53,I was concerned about getting or spreading...,3527987,1115409,1230971,425756,91237,664614
54,I was sick (not coronavirus related) or di...,6722545,2317380,2325786,952557,297695,829127
55,I am retired,42189378,31424306,5634389,890413,88532,4151738
56,I was laid off or furloughed due to corona...,7218299,2586018,2085350,892520,182851,1471560
57,My employer closed temporarily due to the ...,2740044,904449,604005,476477,91926,663188
58,My employer went out of business due to th...,2040314,429186,513804,518718,176553,402052
59,I did not have tranportation to work,828852,202681,142581,157207,57841,268542
60,Other reason,16620625,7859047,3596568,1408095,474800,3282115
61,Did not report reason,151096377,94269333,22227824,7307130,1512056,25780035
62,Household income,,,,,,
63,"Less than $25,000",23732207,10515340,7528310,4389243,1223597,75718
64,"$25,000 - $34,999",18636048,10043422,5433349,2487504,562012,109760
65,"$35,000 - $49,999",20811511,13141059,5535377,1860203,263995,10877
66,"$50,000 - $74,999",28507113,21090818,5909950,1311151,176337,18856
67,"$75,000 - $99,999",22332718,17991880,3611709,623690,73919,31521
68,"$100,000 - $149,999",25329184,22142307,2669270,394102,107075,16430
69,"$150,000 - $199,999",11861913,10869429,914863,60714,9083,7824
70,"$200,000 and above",12896711,12195005,601818,31531,64377,3980
71,Did not report,86158044,30982332,9498824,3456377,1102476,41118036
72,Used in the last 7 days to meet spending needs*,,,,,,
73,Regular income sources like those received...,157720993,125757576,24278613,5421285,990163,1273357
74,Credit cards or loans,54645825,32294484,15587943,5174040,1054888,534470
75,Money from savings or selling assets or po...,41521270,21636887,13793144,4594597,1040768,455875
76,Borrowing from friends or family,18837177,4405538,6426890,6266183,1536510,202055
77,Unemployment insurance (UI) benefit payments,15322178,7581719,5115826,1989045,415869,219718
78,Stimulus (economic impact) payment,58589746,32444836,18071086,6320701,1188932,564190
79,Money saved from deferred or forgiven paym...,6831229,3178119,2445455,812501,258268,136886
80,Supplemental Nutrition Assistance Program ...,13065439,4941992,4658697,2624601,637683,202466
81,Other,6356731,3248901,1496760,784212,677831,149027
82,Did not report,43237640,2911323,647694,359103,217426,39102093
83,Household receives benefits from the Supplemen...,,,,,,
84,Yes,24482444,10825575,8046708,4427348,1088248,94565
85,No,181572364,136107958,32726968,10015474,2310916,411049
86,Did not report,44210641,2038059,929795,171693,183707,40887388
87,"Frequency of feeling nervous, anxious, on edge",,,,,,
88,Not at all,90263384,77668430,9583043,2278526,524464,208920
89,Several days,52338911,35717943,12680023,3565303,273260,102383
90,More than half the days,20249537,10954171,6292711,2564305,420540,17809
91,Nearly every day,28258033,12684293,8699356,4878902,1945722,49760
92,Did not report,59562952,12325507,4436862,1298123,415479,41086981
93,Covered by health insurance,,,,,,
94,Yes,168220845,125001251,31314225,9441900,2166257,297212
95,No,17283920,8186766,4911955,3246164,914514,24522
96,Did not report or don’t know,64760684,15783575,5477291,1926451,502099,41071268

In [ ]:
# Save the data to file and print a confirmation message
week29_data.to_excel("week29_data_cleaned.xlsx", index=False)
print("File saved.")

File saved.